### ISSUE TITLE
build demo client setup tool

### ISSUE THREAD

**Issue by warner** [Agoric/cosmic-swingset#11]
The demo-client setup tool will accept the magic-wormhole code emitted by the provisioning server (#10) and run `ag-solo init`, send the generated pubkey to the server, accept the blob it returns, configure the solo node with that data, then launch `ag-solo start`. It will need to be written in python to use the wormhole code.

**Comment by michaelfig** [comment]
This almost works.  The current error:

```
Provisioning code: 5-atlantic-accrue
server message is {'ingressIndex': 1, 'rpcAddrs': ['104.248.229.45:26657', '142.93.154.211:26657'], 'chainName': 'mfig13', 'ok': True, 'gci': 'a7784cc198fc86f1dc45ad12f3dad3688fc2bdfa399231cd69ca37506c4edb39'}
solo [
  'set-gci-ingress',
  '--chainID=mfig13',
  'a7784cc198fc86f1dc45ad12f3dad3688fc2bdfa399231cd69ca37506c4edb39',
  '104.248.229.45:26657',
  '142.93.154.211:26657'
]
solo [ 'start' ]
adding HTTP/WS listener on 127.0.0.1:8000
Serving static files from /usr/src/app/solo/agoric/html
adding follower/sender for GCI a7784cc198fc86f1dc45ad12f3dad3688fc2bdfa399231cd69ca37506c4edb39
= loading config from basedir /usr/src/app/solo/agoric/vats
ignoring  bootstrap.js
ignoring  gci.js
ignoring  repl.js
Listening on 127.0.0.1:8000
initial state is {}
kernel.addDevice(mailbox)
kernel.addDevice(command)
= adding vat 'comms' from /usr/src/app/solo/agoric/vats/vat-comms.js
= adding vat 'demo' from /usr/src/app/solo/agoric/vats/vat-demo.js
= adding vat 'http' from /usr/src/app/solo/agoric/vats/vat-http.js
= adding vat 'mint' from /usr/src/app/solo/agoric/vats/vat-mint.js
= adding vat 'provisioning' from /usr/src/app/solo/agoric/vats/vat-provisioning.js
= adding vat 'vattp' from /usr/src/app/node_modules/@agoric/swingset-vat/src/vat-tp/vattp.js
loading bootstrap.js
=> queueing bootstrap()
adding vref _bootstrap
adding vref comms
adding vref demo
adding vref http
adding vref mint
adding vref provisioning
adding vref vattp
adding dref command
adding dref mailbox
bootstrap() called
about to return {"@qclass":"undefined"} []
cs[comms].dispatch.deliver 0.init -> 30
about to return {"@qclass":"undefined"} []
cs[comms].dispatch.deliver 0.addIngress -> 31
unable to find key incoming-a7784cc198fc86f1dc45ad12f3dad3688fc2bdfa399231cd69ca37506c4edb39-your-ingress-1
cs[comms].dispatch.deliver 0.addIngress -> 32
unable to find key incoming-a7784cc198fc86f1dc45ad12f3dad3688fc2bdfa399231cd69ca37506c4edb39-your-ingress-2
deliver {}
swingset running
new block on a7784cc198fc86f1dc45ad12f3dad3688fc2bdfa399231cd69ca37506c4edb39, fetching mailbox
(node:17) UnhandledPromiseRejectionWarning: Error: Command failed: ag-cosmos-helper query swingset mailbox cosmos1umzphhtmkj7eh06469xp3q8dvhw4m66903yg2t --chain-id mfig13 --output json --home /usr/src/app/solo/agoric/ag-cosmos-helper-statedir
    at checkExecSyncError (child_process.js:631:11)
    at execFileSync (child_process.js:649:15)
    at getMailbox (/usr/src/app/lib/ag-solo/chain-cosmos-sdk.js:41:20)
    at LightNode.<anonymous> (/usr/src/app/lib/ag-solo/chain-cosmos-sdk.js:90:29)
    at LightNode.emit (events.js:201:15)
    at LightNode.EventEmitter.emit (domain.js:471:20)
    at LightNode.update (/usr/src/app/node_modules/tendermint/lib/lightNode.js:251:12)
    at LightNode.syncTo (/usr/src/app/node_modules/tendermint/lib/lightNode.js:157:20)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async LightNode.<anonymous> (/usr/src/app/node_modules/tendermint/lib/lightNode.js:207:11)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by warner** [comment]
I don't quite know what's going on there. If you run that same `ag-cosmos-helper query` command manually, does it fail with any useful message? I wonder if the chain is not yet ready to be queried.

**Comment by michaelfig** [comment]
I found and fixed this problem.  ag-cosmos-helper was trying to connect to localhost, which is not necessarily a chain node.

Now, with the code in master (and @katelynsills SwingSet fixes for Agoric/cosmic-swingset#18), I get:

```
adding vref vattp
adding dref command
adding dref mailbox
bootstrap() called
about to return {"@qclass":"undefined"} []
cs[comms].dispatch.deliver 0.init -> 30
about to return {"@qclass":"undefined"} []
cs[comms].dispatch.deliver 0.addIngress -> 31
unable to find key incoming-d5bbdebf3eca34c6a882f3b5bc00dfef4b2823936de307367144952f9c54a03b-your-ingress-1
cs[comms].dispatch.deliver 0.addIngress -> 32
unable to find key incoming-d5bbdebf3eca34c6a882f3b5bc00dfef4b2823936de307367144952f9c54a03b-your-ingress-2
deliver {}
swingset running
new block on d5bbdebf3eca34c6a882f3b5bc00dfef4b2823936de307367144952f9c54a03b, fetching mailbox

 helper said: {"value":"{\"outbox\":[], \"ack\":0}"}
[more fetching mailbox messages...]
```

This code is now running on the testnet, so you should be able to debug with your local copy of ag-setup-solo.

Are the `unable to find key` messages something that needs fixing?

**Comment by warner** [comment]
nope, those are benign. I think I removed them in the most recent SwingSet, or maybe in the next release.

The setup process looks good, closing this now.

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 11
