### ISSUE TITLE
monorepo

### ISSUE THREAD

**Issue by warner** [Agoric/cosmic-swingset#126]
We're considering moving SwingSet, cosmic-swingset, and some related packages into a monorepo.

## The Problem

It's currently pretty difficult to run cross-package tests. Chris has run into many of these, while implementing the Timer Device (which lives in SwingSet but must be configured to use host-specific sources of timing in cosmic-swingset). This also hit JF while working on the wallet/exchange demo, where it wasn't convenient to run anything beyond scenario3 (no-chain, everything in a single process), so the vats didn't get partitioned properly to work under scenario2 or 1 (actual chains). ERTP and Zoe have extensive unit tests, but we don't have a good place to run integration tests, to see how they behave in an actual chain environment.

`cosmic-workspace` is a response to this, a git-submodule -based "monorepo", currently using [Lerna](https://lerna.js.org/) for setup. Michael uses it to manage the testnet, and updates the component modules (to the most recent release of that package) each time the testnet needs updating. However:

* we don't have any integration tests
* manipulating submodules (editing, branching, submitting PRs) is a hassle, especially because git submodules (correctly) record only a specific commit-id, not a branch
* it's confusing to sometimes do editing and unit-testing work in the submodule, and sometimes do it in a direct checkout of the given project

A "real" monorepo would be the canonical git home of all of the projects it contains, rather than using git submodules to fake it. It would not necessarily be restricted to having the most recent release of all the projects it contains.

## Mechanics

We'll probably use [these tools](https://github.com/shopsys/monorepo-tools) to build a new repo that contains the full history of each project (rewritten into the same number of commits, with the same author/timestamp/comment, but which puts the code in a subdirectory), along with a final big N-parent merge commit. We'll use [lerna](https://lerna.js.org/) and Yarn to handle the installation process, which recognizes when one package depends upon another one in the same repo, and replaces the `node_modules/` directory with a symlink.

We'll have integration tests in the top of the repo, and unit tests in each separate package.

We might put the results in the `agoric-sdk` repo on GitHub, or maybe create a new one.

The rule will be that the current trunk (`master`) of this repository should pass all integration tests, and the unit tests of each package.

We must decide whether to release all the packages in the monorepo at the same time (with the same version number, abandoning semver), or release individual packages (each with their own version number) only when their changes warrant a new release.

## What to Include

At least: `swingset`, `cosmic-swingset`.

Probably `bundle-source`, `captp`.

Maybe `eventual-send` and `acorn-eventual-send`, which provide support for the tildot (`x~.foo(args)`) operation.

Quite possibly `ertp` and `zoe`. I think a lot of the "does this all work together" questions that would be easier to test/ansewr in a monorepo will involve these two. Basically everything that goes into the "central services" in an Agoric platform, and maybe even a bunch of the client-side stuff.

We might even want to put `agoric-sdk` here too, since the purpose of the SDK is to produce an `agoric` executable that will need to import or install copies of many of the other repos. That would suggest we also include `wallet-frontend`, and maybe `autoswap-frontend` as an example.

We think SES will remain as a separate (mono)repo, which will include `evaluator-shim`, Realms stuff, and module loader packages.

## Pros

* we'll have a place for integration tests that execute more of the Agoric platform
* it will be easier to test multi-package changes that affect cross-package compatibility
  * we anticipate doing a lot of this in the near future, as we clean up "Central Services" and our platform in general
* 

## Cons

* releasing all packages at the same time (with the same version number) is easier to manage, but abandons semver semantics (most packages will see multiple identical releases, prompted only by the need to release changes in other packages)
* releasing packages separately will cause a difference between the monorepo's trunk (which we test on a regular basis, with CI), and the current releases on NPM (as used by downstream users)
* monorepos in general favor developers of the packages over downstream users of those packages

**Comment by katelynsills** [comment]
I like the idea of ERTP and Zoe being part of this.

**Comment by warner** [comment]
I'm inclined to use `agoric-sdk` as the name of the monorepo. We're currently (for about the last week) using that repo for the `bin/agoric` command that developers use/will-use to set up a development environment. If we claim that repo name for the monorepo, then the CLI tool will move into a subdirectory (maybe `packages/sdk` or `packages/agoric`). Most platform developers will do most of their work inside a checkout of the `agoric-sdk` repo. Our users (developing dapps and contracts) will `npm install -g agoric`, which comes from a subdirectory of `agoric-sdk`.

Repos to merge in (and their most recent version tags, with `+` meaning there are unreleased commits in the repo) (and the number of open/closed issues):

* cosmic-swingset (v0.10.15) (24/39)
* SwingSet (swingset-vat) (v0.3.0) (50/48)
* bundle-source (v1.0.2) (1/0)
* default-evaluate-options (v0.2.7) (0/0)
* evaluate (v2.1.3) (0/1)
* eventual-send (v0.4.4+) (7/17)
* acorn-eventual-send (v2.0.0) (0/0)
* marshal (v0.1.1) (3/3)
* captp (v1.0.2+) (2/1)
* ERTP (v0.1.11+) (33/47)
* agoric-sdk (v0.3.1) (1/1)

Repos to leave out:

* harden (part of the [SES-shim monorepo](https://github.com/Agoric/SES-shim))
* nat (tiny, hasn't changed for a while)

And I'll recommend using separate version numbers and release schedules for all the packages. If we went to a single common version, it would have to be at least "2.1.4" (since `evaluate` is already at 2.1.3), and we just have too many breaking changes to add to suggest that SwingSet or cosmic-swingset is worthy of a 1.x or 2.x release. That means our git tags will need to include the package name, like `bundle-source-v1.0.2` instead of just `v1.0.2`. Most of these live under the `@agoric/` NPM namespace, which we'll leave out of the tag name (so `bundle-source-v1.0.2` instead of `agoric-bundle-source-v1.0.2`).

The inter-package compatibility rule will be:

* 1: Everything in the trunk (master branch) of the monorepo must work with everything else in the trunk. Our CI should enforce this by doing a top-level `lerna (something)` and then running unit tests for all packages, which will use all the other trunk packages.
* 2: Each package must work with its declared dependencies. CI will (in a different checkout) run `yarn install` inside each package separately and then `yarn test`. This will ignore the other packages in the monorepo.
* 3: The most recent release of all packages must work together. I'm not sure how we'll test this, maybe a nightly CI that examines all the tags or npmjs.com metadata to figure out the current releases, and then builds a monorepo-like tree that contains the package contents for those versions, then does lerna-like cross-linking, then runs the unit tests in each package.

And that means most of the time the monorepo packages should be sitting at a release, rather than having a lot of unreleased commits (we should be comfortable with making releases frequently). Maybe we should aim for a weekly cycle (e.g. just before updating the testnet) of releasing anything with unreleased commits. If we can pull that off, then the CI we run on each checkin will also exercise compatibility rule 3. I expect that only the top few packages (agoric-sdk, cosmic-swingset) are likely to have long-lived unreleased commits, and that number will go down as we find better ways to factor the packages.

**Comment by michaelfig** [comment]
Looks good.  I just released eventual-send v0.4.5, as it contains some useful fixes.  Can you import it?

**Comment by katelynsills** [comment]
I can release a new version of ERTP today that includes the last minute changes from the hackathon, too.

**Comment by michaelfig** [comment]
I would suggest moving the existing `agoric-sdk` to `packages/agoric-cli`.

**Comment by katelynsills** [comment]
Ok, version 1.12 of ERTP is released!

**Comment by michaelfig** [comment]
I released v1.1.0 of captp, which incorporates doc fixes and a new `abort` method (so that you don't have to dispatch a magic packet to close a connection).

**Comment by warner** [comment]
sounds good, I'll incorporate those versions, and move the SDK stuff into `packages/agoric-cli`

**Comment by michaelfig** [comment]
BTW, what will we do for issues?  Are we going to transfer them all to `agoric-sdk` and archive the other repos?

**Comment by warner** [comment]
huh, `monorepo-tools` has a mode that lets you push changes *back* into the original single-package repositories, which suggests they're thinking of some kind of hybrid mode, where the single-package repos are followers of the monorepo. I'm not sure what to think of that yet.

For issues.. good question. I guess we start with a convention of prefixing each issue with a `[$PACKAGE]` string to remind us which package is most relevant, and/or use Labels for that purpose. Transferring and archiving makes the most sense to me. That does sound like a lot of bug movement though.

**Comment by warner** [comment]
Hrm, `monorepo_build.sh` merged all the tags of all the original packages together, which is mostly unusable. I'll look into writing something that renames tags to be package-specific.

**Comment by warner** [comment]
The `monorepo-tools` [blog post](https://blog.shopsys.com/how-to-maintain-multiple-git-repositories-with-ease-61a5e17152e0) says they're also publishing read-only individual repositories for each project. So they do all their development in the monorepo, but downstream users can clone just one thing at a time if they don't care to look at the whole thing.

I'm not sure that'd be a win for us, but it explains why they have a split tool.

**Comment by warner** [comment]
Rather than moving the packages into subdirs like `packges/SwingSet` and `packages/ERTP`, I think I'm going to put them in top-level subdirectories (so `SwingSet/` is a sibling of the top-level `packages.json` and `yarn-lock.json` and `lerna.json`).

I use tab-completion a lot, and the shared prefix between `packages/(anything)` and `package.json` is pretty annoying. It looks like `lerna.json`can be configured with either a glob (like `packages/*`) or an explicit list of packages. I'm willing to edit this file each time we add a package, in exchange for getting to type `Sw<TAB>` or `cos<TAB>` to jump to `SwingSet` or `cosmic-swingset`.

It looks like `packages/*` is the default. Does anyone know of a reason why choosing a non-default location is likely to cause problems??

**Comment by michaelfig** [comment]
That's worked for me in cosmic-workspace.

**Comment by warner** [comment]
Ok, I've got a proposed repo in place in https://github.com/agoric-labs/swingset-monorepo-experiment-3 .

I had to write a new script to build the Git history I wanted. `monorepo-tools` creates a new history, which contains a one commit for each original commit, with author/timestamp/comments the same, but the filepaths are all moved down by a subdirectory. As a result all the commit IDs are changed. With my script, the entire original history is imported unmodified (same commit IDs), then there's a commit that moves e.g. all of SwingSet's files down into `SwingSet/`, then there's a big merge commit that combines the ten unrelated histories into a single tree.

My script also creates new tags with names like `SwingSet-v1.2.3` for every `v1.2.3` in the original package.

I set up a GitHub Actions CI build. It takes about 5 minutes to run, and it does:

* install `lerna` (`yarn` is already installed)
* runs a `bootstrap` command to get all the `node_modules` symlinks set up, and compiles all the Go code (takes about 3 minutes)
* runs `yarn test` to run unit tests in all packages (takes about one minute)

I'm hoping to build some smaller CI jobs that run tests in single packages, so that PRs can get results earlier (e.g. if a PR only changes something in `eventual-send`, it should only take maybe 30s to run just those unit tests, and we shouldn't try to compile all the Go code in that run).

The `package.json` and `lerna.json` files kinda work, but I'm sure they aren't ideal.. would love some feedback on them. It looks like yarn knows how to use `lerna`, but if I use a `yarn install` then it doesn't respect the `--force-local` flag that I think I want.

There is likely breakage that needs to be checked and fixed:

* All the `.gitignore` files are now in the wrong directories, so paths that are expressed as relative to the top of the project (e.g. `/node_modules`) will no longer ignore the right thing. I saw two cases where this resulted in files that were both checked in and ignored, or something equally weird: `agoric-sdk/template/ui/.env.local` and `SwingSet/src/bundles/README.md`.
* Maybe the same for `.npmignore`
* I have no idea if we can still publish packages from the subdirectories of this repo. The `package.json` contents (in particular the `files` key) might not longer be accurate.
* I think we're moving from NPM to Yarn in this process, and we still have `package-lock.json` files in each subdirectory. I *think* we want to delete these and instead have a `yarn-lock.json` at the top level, but I'm not sure. And we still need to build it.
* We probably want to merge the various `.eslintrc.js` and `.prettierrc.json` files, have them live only in the top-level.

If this works out, my plan is to push it to the `agoric-sdk` repo (they have a shared history, so it will be a fast-forward merge), and then start migrating tickets over.

I'm still a bit concerned about the tradeoff between making cross-package testing easier, vs making single-package testing/development more expensive. Running unit tests just in a single package should be fine, but PRs will (generally) be slower to CI if they're also always testing all the interactions. One might argue that we very much want this integration testing to happen on each PR, but I'll be interested to hear about how the developer experience changes.

**Comment by warner** [comment]
more progress: https://github.com/agoric-labs/swingset-monorepo-experiment-5/ is fully self-compatible (`yarn workspaces info` reports no `mismatchedWorkspaceDependencies`), runs the full `yarn test` suite on each checkin in about 4.5min, and has a single shared `yarn.lock` instead of separate `package-lock.json` files in each package.

I pushed some `package.json` changes into the upstream repos to support this (removing the `-dev.0` post-release versions, and updating dependencies to be mutually compatible).

My next checks are to get `eslint` working in a shared fashion, and to make sure that `npm pack` in the subdirectories produce tarballs that match the most recent release (so maybe we'll be able to `npm publish` from there). And I want to write up the `npm version`/`npm publish` recipe.

**Comment by warner** [comment]
Oh and I'm curious if people think we should add `default-evaluate-options`, `transform-eventual-send` and/or `babel-parser` to the monorepo. These are the three agoric-namespaced packages that are used by the monorepo but don't yet live inside. (I'm omitting `Nat`, `harden`, and `make-hardener`, as these feel more like SES things).

**Comment by warner** [comment]
@michaelfig says we should include `@agoric/default-evaluate-options` and `@agoric/transform-eventual-send`, but not `@agoric/babel-parser` (which is a fork of upstream).

**Comment by warner** [comment]
I added those two. We need to remove a `.dev0` from transform-eventual-send (https://github.com/Agoric/transform-eventual-send/pull/7), and I'm getting an error when running `yarn build` in `default-evaluate-options`:

```
warner@agony:~/trees/swingset-monorepo-experiment-6/packages/default-evaluate-options$ yarn build
yarn run v1.19.1
$ rollup -c

src/index.js → dist/default-evaluate-options.umd.js, dist/default-evaluate-options.esm.js, dist/default-evaluate-options.cjs.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@agoric/eventual-send (imported by src/index.js)
@agoric/transform-eventual-send (imported by src/index.js)
[!] Error: 'parse' is not exported by ../../node_modules/@agoric/babel-parser/lib/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/index.js (1:9)
1: import { parse } from '@agoric/babel-parser';
            ^
2: import generate from '@babel/generator';
3: import makeEventualSendTransformer from '@agoric/transform-eventual-send';
Error: 'parse' is not exported by ../../node_modules/@agoric/babel-parser/lib/index.js
    at error (/home/warner/trees/swingset-monorepo-experiment-6/node_modules/rollup/dist/rollup.js:5351:30)
    at Module.error (/home/warner/trees/swingset-monorepo-experiment-6/node_modules/rollup/dist/rollup.js:9650:9)
    at handleMissingExport (/home/warner/trees/swingset-monorepo-experiment-6/node_modules/rollup/dist/rollup.js:9567:21)
    at Module.traceVariable (/home/warner/trees/swingset-monorepo-experiment-6/node_modules/rollup/dist/rollup.js:9958:17)
    at ModuleScope.findVariable (/home/warner/trees/swingset-monorepo-experiment-6/node_modules/rollup/dist/rollup.js:8627:39)
    at Identifier$1.bind (/home/warner/trees/swingset-monorepo-experiment-6/node_modules/rollup/dist/rollup.js:4381:40)
    at CallExpression$1.bind (/home/warner/trees/swingset-monorepo-experiment-6/node_modules/rollup/dist/rollup.js:3126:31)
    at CallExpression$1.bind (/home/warner/trees/swingset-monorepo-experiment-6/node_modules/rollup/dist/rollup.js:6335:15)
    at SpreadElement.bind (/home/warner/trees/swingset-monorepo-experiment-6/node_modules/rollup/dist/rollup.js:3130:23)
    at SpreadElement.bind (/home/warner/trees/swingset-monorepo-experiment-6/node_modules/rollup/dist/rollup.js:7908:15)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Repo is in https://github.com/agoric-labs/swingset-monorepo-experiment-6 if anyone wants to try to figure out the problem.

**Comment by warner** [comment]
I'm now looking at the lint status, after merging all the eslint/prettier-related `devDependencies` into the top-level package.json. Most of the packages fail `npm run lint-check` when I run it in the original (non-mono) repository, but three of them (ERTP, SwingSet, and a third I forget) were lint-clean in the original but not in the monorepo. The complaints are mostly about line lengths, which makes me think that some of our customizations or settings aren't getting picked up properly.

My plan is to get those three fixed, then add CI which checks them on each commit. I'll hold off trying to make everything else lint-clean.

**Comment by michaelfig** [comment]
I could only get the rollup to work if all the `default-evaluate-options` dependencies are installed in `default-evaluate-options/node_modules`, including `rollup`.  Both the independent package and the lerna repo did that.

If the current monorepo does not do that, we can hack it the way I used to in the package.json:
```js
  "build": "npm ci && rollup -c",
```

**Comment by warner** [comment]
hm. Yeah, that sounds like a decent short-term workaround, although it kind of defeats the purpose of having a monorepo (assuming `default-evaluate-options/node_modules/` will get its own copy of `eventual-send` and `transform-eventual-send` directly from npmjs.org), so let's remember to try and fix that eventually.

**Comment by warner** [comment]
see https://github.com/Agoric/default-evaluate-options/issues/2 and the associated PR for a different fix

**Comment by warner** [comment]
The monorepo is open for business at https://github.com/Agoric/agoric-sdk . Look in `packages/cosmic-swingset/` for the code from this repo. Quick instructions for setup are at the top level. Note that you'll need `yarn` and golang installed before you can do the initial `yarn install` and `yarn build` and `yarn test`. I'm still in the process of migrating issues and locking the old repos (removing all files, leaving a README with a pointer to the new home).

**Comment by warner** [comment]
Note that I won't be able to migrate PRs. However because the monorepo and each source repo share history, if your PR doesn't introduce any new files, you should be able to rebase it across the monorepoization commit (which just moves everything from the old repo down into a subdirectory). I haven't written up docs on that yet, but if you're comfortable with git, then pick a branch name and basically do:

* in your `agoric-sdk` tree, add e.g. `https://github.com/Agoric/cosmic-swingset` as a new remote
* `git fetch cosmic-swingset refs/pulls/NN/head`
* `git branch $name FETCH_HEAD`
* `git checkout $name`
* `git rebase master`

Then push `$name` to the `agoric-sdk` repo and create a new PR, perhaps including a link to the original one in the comments so any earlier discussion is available.

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 126
