### ISSUE TITLE
"match" of null error, when launching "ag-chain-cosmos start"

### ISSUE THREAD

**Issue by erights** [Agoric/cosmic-swingset#34]
Relevant part of log:

```
bootstrap(--role=chain ) called
doProcess: vat[_bootstrap][0].bootstrap dispatch failed: TypeError: Cannot read property 'match' of null TypeError: Cannot read property 'match' of null
    at argv.forEach.arg (/Users/markmiller/src/ongithub/agoric/cosmic-swingset/lib/ag-solo/vats/bootstrap.js:14:23)
    at Array.forEach (<anonymous>)
    at parseArgs (/Users/markmiller/src/ongithub/agoric/cosmic-swingset/lib/ag-solo/vats/bootstrap.js:13:8)
    at Object.bootstrap (/Users/markmiller/src/ongithub/agoric/cosmic-swingset/lib/ag-solo/vats/bootstrap.js:36:40)
    at Promise.resolve.then._ (/Users/markmiller/src/ongithub/agoric/cosmic-swingset/node_modules/@agoric/swingset-vat/src/kernel/liveSlots.js:359:23)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
checkpointed mailbox state: 2 bytes
Returned from SwingSet undefined <nil>
```

**Comment by warner** [comment]
I ran into this when the way I started the chain didn't specify a `BOOTSTRAP` address (as belied by that suspicious extra space between `--role=chain` and `)`). I think this sometimes passed in as an environment variable, from the Makefile.

What was the command you used to start the chain that time?

We should probably change that startup process to tolerate the lack of a provisioner/controller node, and leave out the BOOTSTRAP stuff in that case.

**Comment by erights** [comment]
> What was the command you used to start the chain that time?

I don't know how I'd reconstruct it at this point. Perhaps in my shell history? What should I look for?

**Comment by michaelfig** [comment]
Closing as stale.  Please reopen if you have this problem again while following the new README.

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 34
