### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/cosmic-swingset#51]
I'm on Linux (Ubuntu Disco Dingo)\
I followed the readme instruction and get the following from the install

```sh
david@ZIENA:~/projects/cosmic-swingset (master)$ npm install

> @agoric/cosmic-swingset@0.7.9-dev.0 preinstall /home/david/projects/cosmic-swingset
> make all

GO111MODULE=on go build -v -buildmode=c-shared -o lib/libagcosmosdaemon.so lib/agcosmosdaemon.go
runtime/cgo
net
command-line-arguments
install_name_tool -id `pwd`/lib/libagcosmosdaemon.so lib/libagcosmosdaemon.so
/bin/sh: 1: install_name_tool: not found
make: [Makefile:111: compile-go] Error 127 (ignorée)
# Not needed, because we librarify ./cmd/ag-chain-cosmos as ./lib/libagcosmosdaemon.so
#GO111MODULE=on go install -tags " ledger" ./cmd/ag-chain-cosmos
GO111MODULE=on go install -v -tags " ledger" ./cmd/ag-cosmos-helper
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.

audited 1373 packages in 31.409s
found 0 vulnerabilities
```

**`/bin/sh: 1: install_name_tool: not found`** feels particularly relevant

This leads to `ag-chain-cosmos --help` not working (`ag-cosmos-helper` works fine) 
 
I'm going to try to solve this and post my findings here

**Comment by michaelfig** [comment]
The `install_name_tool` message is misleading.  It's only necessary on Mac OS, and its failure elsewhere causes no problem.

I'll update the build so it doesn't look wrong on non-mac platforms.  However, your problem is caused by something else.

**Comment by DavidBruant** [comment]
Thanks for the info
Do you have an idea of what might be causing the problem?

If relevant, output of when i try `ag-chain-cosmos`:

```
david@ZIENA:~/projects/cosmic-swingset (master)$ ag-chain-cosmos --help
Error: Could not locate the bindings file. Tried:
 → /home/david/projects/cosmic-swingset/build/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/build/Debug/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/build/Release/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/out/Debug/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/Debug/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/out/Release/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/Release/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/build/default/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/compiled/12.8.0/linux/x64/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/addon-build/release/install-root/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/addon-build/debug/install-root/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/addon-build/default/install-root/agcosmosdaemon.node
 → /home/david/projects/cosmic-swingset/lib/binding/node-v72-linux-x64/agcosmosdaemon.node
    at bindings (/home/david/projects/cosmic-swingset/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/david/projects/cosmic-swingset/lib/ag-chain-cosmos:17:33)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11 {
  tries: [
    '/home/david/projects/cosmic-swingset/build/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/build/Debug/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/build/Release/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/out/Debug/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/Debug/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/out/Release/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/Release/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/build/default/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/compiled/12.8.0/linux/x64/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/addon-build/release/install-root/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/addon-build/debug/install-root/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/addon-build/default/install-root/agcosmosdaemon.node',
    '/home/david/projects/cosmic-swingset/lib/binding/node-v72-linux-x64/agcosmosdaemon.node'
  ]
}
```

**Comment by DavidBruant** [comment]
I'm very familiar with node.js/npm but total newbie in Golang

**Comment by michaelfig** [comment]
Did you run `npm run build`?  That's where `agcosmosdaemon.node` is generated.

Maybe that step is missing from the documentation.

**Comment by DavidBruant** [comment]
oh no, i missed that part :-p
I'll try and come back to the issue

**Comment by DavidBruant** [comment]
ok, now `ag-chain-cosmos --help` works but `ag-cosmos-helper --help` doesn't any longer. It gives the following issie
```
david@ZIENA:~/projects/cosmic-swingset (master)$ ag-cosmos-helper --help
docker: network "host" is specified multiple times.
See 'docker run --help'.
```

Reading from the code 
https://github.com/Agoric/cosmic-swingset/blob/4d4cbf11c93026e69d5b5f9ae7738a2f73c6f8bc/docker/ag-cosmos-helper#L18-L42
It looks from lines 36 and 40 that `--net=host` may indeed be specified twice (once on the docker command + once via `$FLAGS`)

I don't understand this script yet, but i'll keep digging

**Comment by michaelfig** [comment]
The `--net=host` in line 40 should go away.  It's not needed.

**Comment by DavidBruant** [comment]
Things work on my end, i sent a PR with what we discussed here

Thank you very much @michaelfig for your help and reactivity :-)

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 51
